# Sending Http Requests for testing CarSharing Projectinstead of using Postman

# Request for REGISTERING a new user (specify MANAGER or CUSTOMER in role
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "username": "admin",
  "password": "pw123",
  "role": "MANAGER"
}

###

# Request for LOGGING in a Manager (for CUSTOMER the JSON body needs to be adapted)
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "pw123"
}


###

# Request for REGISTERING a new VEHICLE (requires Manager token!)
POST http://localhost:8080/api/vehicles
Content-Type: application/json
Authorization: Bearer c4cef5b9-3cde-4dce-93fb-891308a75aba


{
  "name": "Porsche",
  "description": "Familienwagen",
  "statusDetails": {
    "longitude": 48.239189,
    "latitude": 16.376901
  }
}

###


# Vehicle sends its STATUS (requires Vehicle token returned at registerVehicle)

POST http://localhost:8080/api/devices/1/status
Content-Type: application/json
Authorization: Bearer 16a92169-a138-4564-9f88-5d75a6a9efd8

{
        "longitude": 48.239189,
        "latitude": 16.376901,
        "currentTimeStamp": "2024-05-12T12:58:26.274216887",
        "occupyState": "FREE",
        "currentDriver": null,
        "distanceSinceLastUpdate": 4500,
        "timeSinceLastUpdate": 1111
}

###


# Vehicle sends an ALARM (requires Vehicle token returned at registerVehicle)

POST http://localhost:8080/api/devices/1/alarm
Content-Type: application/json
Authorization: Bearer 36db8826-4496-4463-bf41-2394088c3c83

{
  "priority": "HIGH",
  "emergencyDescription": "I hun an Unfall heast!"
}


###

# Generating the Invoice Queue Request

POST http://localhost:8080/api/invoices/1
Content-Type: application/json
Authorization: Bearer c4cef5b9-3cde-4dce-93fb-891308a75aba


###

# Endpoint for occupying a vehicle

POST http://localhost:8080/api/vehicles/1
Content-Type: application/json

{
  "username": "admin"
}